message: Hello There!

test.ext.prop: config subdirectory of current directory

db.driverclass: com.mysql.cj.jdbc.Driver
db.url: jdbc:mysql://localhost:3306/scm
db.username: host
db.password: Password
isSecured: newa
userService: user-service
priceService: price-service
createPrice: /createPrice
getPrice: /getPrice

productService: product-service/product
getProduct: /getProduct

stockService: stock-service/stock
verifyStock: /verifyStock
